### ISSUE TITLE
Apache Drill vs textQL

### ISSUE THREAD

**Issue by doribd** [dinedal/textql#72] opened 2018-04-08 11:05 UTC
Hi
Seems that all or most of the capabilities of your tool being already covered by the Apache Drill + in addition Apache Drill can do a join between csv table to oracle or any other data source that you will define.

Regards,
Dor

**Comment by dinedal** [comment] 2018-04-08 15:45
Duplicate of #71

**Closed by dinedal** 2018-04-08 15:45 UTC
